name: Discord Webhook

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Commit Webhook
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.4
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}